# Terraform Checkov Job
jobs:
  - job: terraformCheckov
    displayName: "Terraform Checkov Scan"
    steps:
      - checkout: self
        fetchDepth: 1
      # Pull Checkov Image and Scan Directory
      - script: |
          docker pull bridgecrew/checkov
          docker run -v $(System.DefaultWorkingDirectory):$(System.DefaultWorkingDirectory) bridgecrew/checkov --directory $(System.DefaultWorkingDirectory)/${{ parameters.workingDirectory }}/ --output junitxml --soft-fail > $(System.DefaultWorkingDirectory)/checkov-scan-report.xml
        displayName: "Checkov Scan"
        condition: always()
      # Publish Checkov Artifacts
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Checkov Report"
        inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)"
          ArtifactName: CheckovReport
        condition: always()
      # Publish Checkov Test Results
      - task: PublishTestResults@2
        displayName: "Publish Checkov Test Results"
        inputs:
          testResultsFiles: "**/*checkov-scan-report.xml"
          testRunTitle: "Checkov Scan"
        condition: always()
      # Remove Checkov Docker Image
      - script: 'docker rmi "bridgecrew/checkov" -f | true'
        displayName: "Remove Checkov Docker Images"
        condition: always()
      - script: echo "Checkov Scan Completed"
        displayName: "Post Scan Log"
